### ISSUE TITLE
Laporan Praktikum 1

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD3204#4]
Buat laporan praktikum dengan format umum

Judul Laporan
Pendahuluan
Metode
Hasil
Diskusi
Kesimpulan
Daftar Pustaka

data dikembangkan seperti penambahan sub bab.

**Comment by riinndescartes** [comment]
Catherine V. P 
2C2220008 IV/A Sains Data
Laporan Praktikum Pertemuan (1) 

https://github.com/riinndescartes/Big-Data-Analytics-Praktikum

**Comment by MulyatiEKaSaputri** [comment]
Mulyati Eka Saputri
2C2220009
Laporan Praktikum (HDFS & Penginstallan Hadoop)
[Uploading MulyatiEkaSaputri_2C2220009_LaporanPraktikum1.pdf…]()

**Comment by IndrNurSukmawati** [comment]
Indri Nur Sukmawati
2C2220010
Laporan Tentang HDFS dan Penginstalan Hadoop
[IndriNurSukmawati_2C2220010_LaporanPraktikum1.pdf](https://github.com/sevinurafni/SD3204/files/14816120/IndriNurSukmawati_2C2220010_LaporanPraktikum1.pdf)


Laporan Cara Memasukan Data ke dalam HDFS
[IndriNurSukmawati_2C2220010_LaporanPraktikum2.pdf](https://github.com/sevinurafni/SD3204/files/14816124/IndriNurSukmawati_2C2220010_LaporanPraktikum2.pdf)

**Comment by tenideinarosa** [comment]
Teni Deinarosa Hermalia
2C2220005
Laporan Praktikum 1 (HDFS dan Penginstalan Hadoop)
[TeniDeinarosaHermalia_2C2220005_LaporanPraktikum1.pdf](https://github.com/sevinurafni/SD3204/files/14816522/TeniDeinarosaHermalia_2C2220005_LaporanPraktikum1.pdf)

**Comment by cahyarahma** [comment]
Cahya Rahmawati
2C2220011
Laporan Praktikum 1  (HDFS Penginstalan Hadoop) dan Laporan tentang HDFS
[Cahya Rahmawati_2C2220011_Tugas Praktikum 1.pdf](https://github.com/sevinurafni/SD3204/files/14820611/Cahya.Rahmawati_2C2220011_Tugas.Praktikum.1.pdf)

Laporan cara memasukan data ke HDFS
[Cahya Rahmawati_2C2220011_laporan praktikum 2.pdf](https://github.com/sevinurafni/SD3204/files/14820643/Cahya.Rahmawati_2C2220011_laporan.praktikum.2.pdf)

**Comment by SilviNurinsan** [comment]
Silvi Nurinsan
2C2220006
Teori HDFS dan Laporan praktikum 1(penginstallan Hadoop)
[SilviNurinsan_2C2220006_tugasPraktikum1.pdf](https://github.com/sevinurafni/SD3204/files/14823033/SilviNurinsan_2C2220006_tugasPraktikum1.pdf)

laporan cara masukan data ke HDFS
[SilviNurinsan_2C2220006_TugasPraktikum2.pdf](https://github.com/sevinurafni/SD3204/files/14823040/SilviNurinsan_2C2220006_TugasPraktikum2.pdf)

**Comment by betrandathariq** [comment]
Betrand Athariq Delpiero F
2C2220001
Laporan Praktikum 1
[BetrandAthariqDelpiero F_2C2220001_BigDataAnalytics_LaporanPraktikum1.pdf](https://github.com/sevinurafni/SD3204/files/14825384/BetrandAthariqDelpiero.F_2C2220001_BigDataAnalytics_LaporanPraktikum1.pdf)

**Comment by tenideinarosa** [comment]
Tugas Praktikum 2
Teni Deinarosa Hermalia
2C2220005
[tugas praktikum2 _Teni Deinarosa Hermalia_2C2220005.pdf](https://github.com/sevinurafni/SD3204/files/14833057/tugas.praktikum2._Teni.Deinarosa.Hermalia_2C2220005.pdf)

**Comment by ashafamultazam** [comment]
Ashafa Multazam - 2C2220012
Laporan praktikum 1
[Ashafa Multazam - 2C2220012.pdf](https://github.com/sevinurafni/SD3204/files/14896025/Ashafa.Multazam.-.2C2220012.pdf)

Laporan praktikum 2
[laporan praktikum 2.pdf](https://github.com/sevinurafni/SD3204/files/14896044/laporan.praktikum.2.pdf)

**Comment by kamalshdq** [comment]
Muhammad Kamal Shidiq - 2C2220003
Laporan Praktikum 1
[Muhammad Kamal Shidiq_2C2220003_BigDataAnalytics_LaporanPraktikum1.pdf](https://github.com/sevinurafni/SD3204/files/14897113/Muhammad.Kamal.Shidiq_2C2220003_BigDataAnalytics_LaporanPraktikum1.pdf)

Laporan Praktikum 2
[Muhammad Kamal Shidiq_2C2220001_TugasPraktikum2.pdf](https://github.com/sevinurafni/SD3204/files/14897114/Muhammad.Kamal.Shidiq_2C2220001_TugasPraktikum2.pdf)

**Comment by RyanHakim24** [comment]
Ryan F. F. Hakim - 2C2220007
Laporan Praktikum 1 dan 2:
https://github.com/RyanHakim24/2C2220007_Ryan_Praktikum1-2_ABD

**Comment by SagaraAndiLS** [comment]
Sagara Andi Ladzuardi Suwarsa
2C2220004

1. Tugas Praktikum 1
![Sagara Andi Ladzuardi Suwarsa_2C2220004_Laporan Praktikum 1.pdf](https://github.com/sevinurafni/SD3204/files/14897265/Sagara.Andi.Ladzuardi.Suwarsa_2C2220004_Laporan.Praktikum.1.pdf)

2. Tugas Praktikum 2
![Sagara Andi Ladzuardi Suwarsa_2C2220004_Laporan Praktikum 2.pdf](https://github.com/sevinurafni/SD3204/files/14897267/Sagara.Andi.Ladzuardi.Suwarsa_2C2220004_Laporan.Praktikum.2.pdf)
